### ISSUE TITLE
Change ConstantPool struct members to usize

### ISSUE THREAD

**Issue by jbalint** [ExcaliburZero/jvm-class-file-parser#3]
these are indexes into the constant pool and it's more convenient to work with them if we store them as usize when they are read.

wanted to get your thoughts before making the change

**Comment by ExcaliburZero** [comment]
Can you give a code example of this kind of change?

**Comment by jbalint** [comment]
from 
```rust
    ConstantString {
        string_index: u16,
    },
```
to
```rust
    ConstantString {
        string_index: usize,
    },
```
the primary purpose is to index into the constant pool table, and changing the type here allows us to avoid the cast
```
class_file.constant_pool[(name_index - 1) as usize]
```

**Comment by ExcaliburZero** [comment]
Yep, that sounds like a reasonable change.

You can feel free to make a PR with the change.

I think the reason I made them `u16` instead of `usize` was due to how they are encoded in the class file and how that dictates their valid values. But this seems like a good usability change, since accessing their corresponding entries in the constant pool sounds like a common task.

You may want to add some validation to the logic for writing the class files to make sure that we error on writing a class file that contains invalid constant pool indices (as restricted by the spec).
